import { simulatedBank } from './simulatedBank.js';

const coreBank = [
  { word: 'beautiful', meaning: '美丽的', grade: '七年级', sentence: 'The Haihe River looks beautiful at night.', translation: '海河在夜晚看起来很美。' },
  { word: 'famous', meaning: '著名的', grade: '七年级', sentence: 'Tianjin is famous for its traditional snacks.', translation: '天津以传统小吃闻名。' },
  { word: 'practice', meaning: '练习', grade: '七年级', sentence: 'We practice speaking English every morning.', translation: '我们每天早上练习说英语。' },
  { word: 'museum', meaning: '博物馆', grade: '七年级', sentence: 'Our class visited the Natural History Museum last Friday.', translation: '上周五我们班参观了自然博物馆。' },
  { word: 'healthy', meaning: '健康的', grade: '七年级', sentence: 'Walking to school is a healthy habit.', translation: '步行上学是一个健康的习惯。' },
  { word: 'careful', meaning: '仔细的', grade: '七年级', sentence: 'Please be careful when you cross the busy street.', translation: '穿过繁忙的街道时请小心。' },
  { word: 'weather', meaning: '天气', grade: '七年级', sentence: 'The weather in Tianjin is windy in spring.', translation: '天津春天的天气多风。' },
  { word: 'invite', meaning: '邀请', grade: '八年级', sentence: 'I will invite my classmates to my birthday party.', translation: '我会邀请同学参加我的生日聚会。' },
  { word: 'improve', meaning: '提高；改善', grade: '八年级', sentence: 'Reading aloud can improve your pronunciation.', translation: '大声朗读能够改善你的发音。' },
  { word: 'environment', meaning: '环境', grade: '八年级', sentence: 'Everyone should help protect the environment.', translation: '每个人都应该帮助保护环境。' },
  { word: 'possible', meaning: '可能的', grade: '八年级', sentence: 'Is it possible to finish the work before lunch?', translation: '午饭前完成这项工作可能吗？' },
  { word: 'journey', meaning: '旅行；旅程', grade: '八年级', sentence: 'The train journey from Beijing to Tianjin is short.', translation: '从北京到天津的火车旅程很短。' },
  { word: 'advice', meaning: '建议', grade: '八年级', sentence: 'My teacher gave me useful advice on English learning.', translation: '老师给了我有用的英语学习建议。' },
  { word: 'traditional', meaning: '传统的', grade: '八年级', sentence: 'We learned about traditional Chinese culture in class.', translation: '我们在课堂上学习了中国传统文化。' },
  { word: 'volunteer', meaning: '志愿者', grade: '八年级', sentence: 'She works as a volunteer at the community centre.', translation: '她在社区中心做志愿者。' },
  { word: 'achievement', meaning: '成就', grade: '九年级', sentence: 'Finishing the project was a great achievement for our team.', translation: '完成这个项目是我们团队的一项重大成就。' },
  { word: 'communicate', meaning: '交流；沟通', grade: '九年级', sentence: 'Good friends communicate with each other honestly.', translation: '好朋友会彼此坦诚交流。' },
  { word: 'knowledge', meaning: '知识', grade: '九年级', sentence: 'Books give us knowledge and help us understand the world.', translation: '书籍给我们知识，帮助我们了解世界。' },
  { word: 'responsible', meaning: '负责任的', grade: '九年级', sentence: 'We should be responsible for our own decisions.', translation: '我们应该为自己的决定负责。' },
  { word: 'encourage', meaning: '鼓励', grade: '九年级', sentence: 'My parents always encourage me to try new things.', translation: '父母总是鼓励我尝试新事物。' },
  { word: 'necessary', meaning: '必要的', grade: '九年级', sentence: 'It is necessary to make a plan before we act.', translation: '行动前制订计划是必要的。' },
  { word: 'influence', meaning: '影响', grade: '九年级', sentence: 'A good teacher can influence students for life.', translation: '一位好老师可以影响学生一生。' },
  { word: 'patient', meaning: '有耐心的', grade: '九年级', sentence: 'You need to be patient when learning a new skill.', translation: '学习新技能时你需要有耐心。' },
  { word: 'valuable', meaning: '宝贵的；有价值的', grade: '九年级', sentence: 'The school trip gave us valuable experience.', translation: '这次学校旅行给了我们宝贵的经验。' },
  { word: 'rang', meaning: 'ring 的过去式：响起', grade: '中考语法', type: 'tense', baseWord: 'ring', grammar: '一般过去时', examYear: 2025, explanation: 'when 引导的从句用过去进行时，突然发生的动作通常用一般过去时。', hint: '留意 when 从句中的 was making，主句描述突然发生的短动作。', sentence: 'The mobile phone rang when I was making a cake with my mother.', translation: '我和妈妈做蛋糕时，手机响了。' },
  { word: 'visited', meaning: 'visit 的过去式：参观', grade: '中考语法', type: 'tense', baseWord: 'visit', grammar: '一般过去时', explanation: 'last weekend 是明确的过去时间，谓语动词用过去式。', sentence: 'We visited the Tianjin Museum last weekend.', translation: '上周末我们参观了天津博物馆。' },
  { word: 'finished', meaning: 'finish 的过去式：完成', grade: '中考语法', type: 'tense', baseWord: 'finish', grammar: '一般过去时', explanation: 'yesterday 是一般过去时的典型时间标志。', sentence: 'Li Ming finished his science project yesterday.', translation: '李明昨天完成了他的科学项目。' },
  { word: 'studying', meaning: 'study 的现在分词：学习', grade: '中考语法', type: 'tense', baseWord: 'study', grammar: '过去进行时', explanation: 'at eight last night 表示过去某一时刻正在发生，结构为 was/were doing。', sentence: 'At eight last night, I was studying for the English test.', translation: '昨晚八点，我正在为英语考试复习。' },
  { word: 'waiting', meaning: 'wait 的现在分词：等待', grade: '中考语法', type: 'tense', baseWord: 'wait', grammar: '过去进行时', explanation: 'when 后的短动作 arrived 发生时，前面的持续动作使用过去进行时。', sentence: 'They were waiting for the bus when the rain arrived.', translation: '下雨时，他们正在等公交车。' },
  { word: 'lived', meaning: 'live 的过去分词：居住', grade: '中考语法', type: 'tense', baseWord: 'live', grammar: '现在完成时', explanation: 'since 2020 表示从过去持续到现在，使用 have/has done。', sentence: 'My family has lived in Tianjin since 2020.', translation: '我们一家从2020年起就住在天津。' },
  { word: 'seen', meaning: 'see 的过去分词：看见', grade: '中考语法', type: 'tense', baseWord: 'see', grammar: '现在完成时', explanation: 'already 常与现在完成时连用，see 的过去分词是不规则形式 seen。', sentence: 'I have already seen that film twice.', translation: '那部电影我已经看过两次了。' },
  { word: 'spoken', meaning: 'speak 的过去分词：说', grade: '中考语法', type: 'tense', baseWord: 'speak', grammar: '一般现在时被动语态', explanation: '主语 English 是动作的承受者，事实陈述用 is + 过去分词。', sentence: 'English is spoken in many countries around the world.', translation: '世界上许多国家都使用英语。' },
  { word: 'built', meaning: 'build 的过去分词：建造', grade: '中考语法', type: 'tense', baseWord: 'build', grammar: '一般过去时被动语态', explanation: '主语 bridge 与 build 是被动关系，且有 in 2019，使用 was + 过去分词。', sentence: 'The new bridge was built in 2019.', translation: '这座新桥建于2019年。' },
  { word: 'help', meaning: 'help：帮助', grade: '中考语法', type: 'tense', baseWord: 'help', grammar: '一般将来时', explanation: 'if 引导的条件状语从句遵循“主将从现”，will 后使用动词原形。', sentence: 'If you ask her politely, she will help you with the problem.', translation: '如果你礼貌地问她，她会帮助你解决这个问题。' },
  { word: 'confident', meaning: '自信的；有信心的', grade: '中考真题', examYear: 2024, sentence: 'We feel confident to win the match because we are training hard.', translation: '我们有信心赢得比赛，因为我们正在努力训练。' },
  { word: 'healthier', meaning: '更健康的', grade: '中考真题', examYear: 2024, sentence: 'Many people think eating at home is healthier than eating in the restaurant.', translation: '许多人认为在家吃饭比在餐馆吃饭更健康。' },
  { word: 'protect', meaning: '保护', grade: '八年级', sentence: 'These shelters protect people from the sun and rain.', translation: '这些住所保护人们免受日晒雨淋。' },
  { word: 'success', meaning: '成功', grade: '八年级', sentence: 'Hard work is the key to success.', translation: '努力是成功的关键。' },
  { word: 'promise', meaning: '承诺；保证', grade: '八年级', sentence: 'I promise to return the book on Monday.', translation: '我保证星期一归还这本书。' },
  { word: 'especially', meaning: '尤其；特别', grade: '八年级', sentence: 'I enjoy outdoor sports, especially cycling.', translation: '我喜欢户外运动，尤其是骑自行车。' },
  { word: 'natural', meaning: '自然的', grade: '八年级', sentence: 'The wetland is a natural home for many birds.', translation: '这片湿地是许多鸟类的天然家园。' },
  { word: 'local', meaning: '当地的', grade: '七年级', sentence: 'The local people are friendly to visitors.', translation: '当地人对游客很友好。' },
  { word: 'prepare', meaning: '准备', grade: '八年级', sentence: 'We need to prepare carefully for the school festival.', translation: '我们需要为校园节认真准备。' },
  { word: 'continue', meaning: '继续', grade: '八年级', sentence: 'After a short break, we continued our journey.', translation: '短暂休息后，我们继续旅程。' },
  { word: 'suggest', meaning: '建议', grade: '九年级', sentence: 'I suggest taking the underground during rush hour.', translation: '我建议在高峰时段乘地铁。' },
  { word: 'discover', meaning: '发现', grade: '八年级', sentence: 'Scientists hope to discover more about the ocean.', translation: '科学家希望发现更多关于海洋的奥秘。' },
  { word: 'public', meaning: '公共的；公众的', grade: '八年级', sentence: 'Please keep your voice low in public places.', translation: '在公共场所请降低音量。' },
  { word: 'convenient', meaning: '方便的', grade: '九年级', sentence: 'The new bus line makes travel more convenient.', translation: '新公交线路让出行更方便。' },
  { word: 'culture', meaning: '文化', grade: '八年级', sentence: 'Food is an important part of every culture.', translation: '饮食是每种文化的重要组成部分。' },
  { word: 'proud', meaning: '骄傲的；自豪的', grade: '八年级', sentence: 'Her parents are proud of her progress.', translation: '她的父母为她的进步感到自豪。' },
  { word: 'waste', meaning: '浪费', grade: '八年级', sentence: 'Do not waste water when you brush your teeth.', translation: '刷牙时不要浪费水。' },
  { word: 'energy', meaning: '能源；精力', grade: '八年级', sentence: 'Turning off the lights can save energy.', translation: '关灯能够节约能源。' },
  { word: 'choice', meaning: '选择', grade: '八年级', sentence: 'Taking the train was a good choice for our trip.', translation: '这次旅行选择乘火车是明智的。' },
  { word: 'active', meaning: '积极的；活跃的', grade: '七年级', sentence: 'She is active in the school reading club.', translation: '她积极参加学校读书会。' },
  { word: 'accept', meaning: '接受', grade: '八年级', sentence: 'He was happy to accept our invitation.', translation: '他很高兴接受我们的邀请。' },
  { word: 'explain', meaning: '解释', grade: '八年级', sentence: 'Could you explain this rule to me again?', translation: '你能再给我解释一下这条规则吗？' },
  { word: 'trust', meaning: '信任', grade: '九年级', sentence: 'Good friends should trust and support each other.', translation: '好朋友应该互相信任和支持。' },
  { word: 'compare', meaning: '比较', grade: '八年级', sentence: 'Do not compare yourself with others all the time.', translation: '不要总是拿自己和别人比较。' },
  { word: 'imagine', meaning: '想象', grade: '八年级', sentence: 'Can you imagine life without the Internet?', translation: '你能想象没有互联网的生活吗？' },
  { word: 'gone', meaning: 'go 的过去分词：去过', grade: '中考语法', type: 'tense', baseWord: 'go', grammar: '现在完成时', explanation: 'has gone to 表示去了某地尚未回来。', sentence: 'Tom has gone to the library, so he is not at home.', translation: '汤姆去图书馆了，所以他不在家。' },
  { word: 'written', meaning: 'write 的过去分词：写', grade: '中考语法', type: 'tense', baseWord: 'write', grammar: '现在完成时', explanation: 'so far 是现在完成时的常见信号，write 的过去分词为 written。', sentence: 'She has written three emails so far.', translation: '到目前为止，她已经写了三封邮件。' },
  { word: 'planted', meaning: 'plant 的过去分词：种植', grade: '中考语法', type: 'tense', baseWord: 'plant', grammar: '一般过去时被动语态', explanation: '主语 trees 与 plant 是被动关系，last spring 指向过去。', sentence: 'Many trees were planted near the river last spring.', translation: '去年春天，河边种了许多树。' },
  { word: 'arrives', meaning: 'arrive 的第三人称单数：到达', grade: '中考语法', type: 'tense', baseWord: 'arrive', grammar: '一般现在时', explanation: '列车时刻表通常使用一般现在时，主语 train 为第三人称单数。', sentence: 'The train arrives at Tianjin Station at half past nine.', translation: '火车九点半到达天津站。' },
  { word: 'working', meaning: 'work 的现在分词：工作', grade: '中考语法', type: 'tense', baseWord: 'work', grammar: '现在进行时', explanation: 'Look! 是现在进行时的信号，结构为 is/am/are doing。', sentence: 'Look! The volunteers are working in the community garden.', translation: '看！志愿者们正在社区花园劳动。' }
];

export const wordBank = [...coreBank, ...simulatedBank];
